server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
      routes:
        - id: testing
          uri: lb://PROBLEMHUB
          predicates:
            - Path=/Algomania/**

        - id: identity-service
          uri: lb://AUTHENTICATIONSERVICE
          predicates:
            - Path=/auth/**

        - id: userservice
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: leaderboard
          uri: lb://LEADERBOARD
          predicates:
            - Path=/leaderboard/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


