server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service  
          predicates:
            - Path=/users/**
        - id: leaderboard
          uri: lb://LEADERBOARD
          predicates:
            - Path=/leaderboard/**
        - id: testing
          uri: lb://PROBLEMHUB
          predicates:
           - Path=/Algomania/**
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
            allowedMethods: 
              - "*"
            allowedHeaders: 
              - "*"
            allowCredentials: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
