spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service  
          predicates:
            - Path=/api/**

    consul:
      host: 20.197.20.39 # If running on a different machine, update this
      port: 8500
      discovery:
        enabled: true
        register: true  # Ensures this service registers itself in Consul

server:
  port: 8080


