
server:
  port: 8010

spring:
  application:
    name: user-service

  cloud:
    consul:
      host: 20.197.20.39 # If running on a different machine, update this
      port: 8500
      discovery:
        enabled: true
        register: true  # Ensures this service registers itself in Consul
